### ISSUE TITLE
Can't install on MacOS

### ISSUE THREAD

**Issue by MatthewHerbst** [laggingreflex/win-node-env#4]
Thanks for creating this!

While I realize that the package is meant to be used on a windows machine, I need to run `npm install --save-optional win-node-env` on my MacOS machine to get it checked into our `package.json` and `package-lock.json` files.

Is there some other way I should go about doing that?

**Comment by laggingreflex** [comment]
That is the recommended way. It won't actually install on Mac/linux.

Having it in optional dependencies will install it only on Windows, whereas on other OSes it'll just leave a warning (that it couldn't install an optional dependency or something). That's the intended behavior.

**Comment by MatthewHerbst** [comment]
Thanks for the quick response!

And right. But does adding something to optional dependencies (via the `npm install` command) make an entry in `package-lock.json`? If I just need to manually add it to `package.json` that's doable, but manually editing `package-lock.json` isn't really possible since the manual edits would potentially be removed the next time the file is updated.

**Comment by laggingreflex** [comment]
>Does adding something to optional dependencies (via the npm install command) make an entry in package-lock.json?

It does. Even if you manually add it to package.json, the very process of `npm install` itself will automatically add it to `package-lock.json`, at least on Windows, not sure if this will always be the case in other OSes.

>but manually editing package-lock.json

Sorry if I implied that that's something that you needed to do, you don't. You only need to do `npm i --save-optional win-node-env`, or manually add it to `package.json`. You need not edit `package-lock.json` manually, probably ever, I believe it should only be modified by the npm command itself.

**Comment by laggingreflex** [comment]
I think I might have just now understood your situation. You're adding it to `package.json`, and since you're on Mac, you don't need to do `npm install` so you're wondering if you should also add an entry manually to `package-lock.json`. Is that the case? If so, I'm not entirely sure. I'd still just try `npm i --save-optional win-node-env`, or do `npm install` after manually adding it to `package.json`. On Mac it shouldn't install and just give a warning, but the npm command should automatically make proper entry in `package-lock.json`

**Comment by MatthewHerbst** [comment]
My issues is that when I do `npm i --save-optional win-node-env` I get an error:

```sh
npm i --save-optional win-node-env
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for win-node-env@0.3.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

The error is very clearly because I can't install it on MacOS. However, I want to run it through `npm install` to be sure that it gets added to our `package-lock.json`. So my problem is that I can't install it meaning I can't generate the correct `package-lock.json`.

**Comment by laggingreflex** [comment]
Hmm I see. I was under the impression that it would simply give a warning and continue. I guess I was mistaken then. <strike>It actually makes sense.. if it couldn't be installed then npm wouldn't know which version to lock down (duh!).</strike> 

In that case you probably do have to add it to `package.json` manually. 

Edit: Do the above and simply run `npm i`

<strike>I'm still not sure what to do with `package-lock.json`. You could add it manually, here's what it looks like:

```json
  "dependencies": {
    "win-node-env": {
      "version": "0.3.0",
      "resolved": "https://registry.npmjs.org/win-node-env/-/win-node-env-0.3.0.tgz",
      "integrity": "sha512-H/yxGp0haK3+WypmQz74F+4XPLVrTUbvV0LVSvZNvouyHnPKfRg+RWZR0hka+W0vmK+XVvQnHucugZ2hIAfBAQ==",
      "optional": true
    }
  }
```
but I can see that keeping it up to date without a Windows machine might be a pain.</strike>

**Comment by laggingreflex** [comment]
<strike>Found a very [relevant thread on npm](https://github.com/npm/npm/issues/17722) about an issue that might arise even if you do add it to `package-lock.json` manually. I may not have thought this through... especially when `package-lock.json` would be involved. I may have to remove this suggestion (to add it as optional dependency) entirely. Probably Only Windows users should install it, as a global dependency.<strike>

**Comment by laggingreflex** [comment]
Actually it seems that adding a dependency in `optionalDependencies` in `package.json` manually and running `npm i` (which will skip it if it isn't supported on that OS) still updates `package-lock.json` just fine! 

I tested this with fsevents (which is a Mac only dependency) on Windows this way, and it added it to `package-lock.json`. 

So to summarize, I think you just need to add it to your `package.json` manually, and run `npm i`

**Comment by MatthewHerbst** [comment]
That worked! Pretty strange that it doesn't work doing `npm install --save-optional win-node-env`. I would even say that's probably a bug in npm. Thanks for the help, and for the package!

**Comment by MatthewHerbst** [comment]
Bug reported: https://npm.community/t/npm-install-save-optional-fails-to-properly-modify-package-package-lock-json-if-it-fails/3446
