### ISSUE TITLE
How to remove or uninstall it 

### ISSUE THREAD

**Issue by shashank99928** [laggingreflex/win-node-env#9]
I ran npm uninstall win-node-env
 npm uninstall -g win-node-env
  npm uninstall -g win-node-env --save

still I was not able to get remove it, 
I was getting this response 
"This command was run via npm module 'win-node-env'"

**Comment by laggingreflex** [comment]
Could you check whether the module is still present both locally and globally? (locally - in your project's `node_modules/win-node-env`, and globally – google how to find global npm install location)

And if this is only happening with this library or others too, like "jest" for example?

**Comment by shashank99928** [comment]
figured it out, it was inside /AppData/Roaming/npm and deleted the .cmd file.
Thank you
